import { LearningResource } from '../types/analysis';

export const resourceCatalog: LearningResource[] = [
  {
    id: 'res_fcc_fullstack',
    title: 'FreeCodeCamp Full Stack Developer Curriculum',
    provider: 'FreeCodeCamp',
    url: 'https://www.freecodecamp.org/',
    type: 'interactive_guide',
    duration: '300 hours',
    skills: ['JavaScript', 'HTML5', 'CSS3', 'React', 'Node.js', 'Express', 'MongoDB'],
    domains: ['fullstack', 'frontend', 'backend'],
    minTier: 'intern',
    maxTier: 'junior',
    description: 'Comprehensive, interactive platform covering full-stack development from basic syntax to full applications.',
    isFree: true,
    featured: true
  },
  {
    id: 'res_odin_project',
    title: 'The Odin Project',
    provider: 'The Odin Project',
    url: 'https://www.theodinproject.com/',
    type: 'interactive_guide',
    duration: '250 hours',
    skills: ['HTML5', 'CSS3', 'JavaScript', 'React', 'Node.js', 'Ruby on Rails', 'Git'],
    domains: ['fullstack', 'frontend', 'backend'],
    minTier: 'entry',
    maxTier: 'junior',
    description: 'A free, open-source curriculum for learning full-stack web development through practical projects.',
    isFree: true
  },
  {
    id: 'res_mdn_web_docs',
    title: 'MDN Web Docs',
    provider: 'Mozilla',
    url: 'https://developer.mozilla.org/',
    type: 'official_docs',
    duration: 'Self-paced',
    skills: ['JavaScript', 'HTML5', 'CSS3', 'Web APIs', 'Performance'],
    domains: ['frontend', 'fullstack'],
    minTier: 'intern',
    maxTier: 'senior',
    description: 'The definitive, free resource for core web technologies and browser APIs.',
    isFree: true,
    featured: true
  },
  {
    id: 'res_react_docs',
    title: 'React Official Documentation',
    provider: 'Meta',
    url: 'https://react.dev/',
    type: 'official_docs',
    duration: 'Self-paced',
    skills: ['React', 'JavaScript', 'UI Design', 'Performance'],
    domains: ['frontend', 'fullstack'],
    minTier: 'entry',
    maxTier: 'senior',
    description: 'The official React documentation including interactive tutorials and deep architectural dives.',
    isFree: true,
    featured: true
  },
  {
    id: 'res_node_best_practices',
    title: 'Node.js Best Practices',
    provider: 'GitHub Open Source',
    url: 'https://github.com/goldbergyoni/nodebestpractices',
    type: 'free_book',
    duration: '20 hours',
    skills: ['Node.js', 'Architecture', 'Security', 'Testing', 'Error Handling'],
    domains: ['backend', 'fullstack'],
    minTier: 'junior',
    maxTier: 'senior',
    description: 'A comprehensive, open-source guide to Node.js architecture and best practices.',
    isFree: true,
    featured: true
  },
  {
    id: 'res_yt_traversy_docker',
    title: 'Docker Crash Course for Absolute Beginners',
    provider: 'Traversy Media',
    url: 'https://www.youtube.com/watch?v=pTFZFxd4hOI',
    type: 'youtube_course',
    duration: '1 hour',
    skills: ['Docker', 'Containers', 'DevOps'],
    domains: ['devops', 'backend', 'fullstack'],
    minTier: 'entry',
    maxTier: 'mid',
    description: 'A practical YouTube crash course on Docker fundamentals and containerizing applications.',
    isFree: true
  },
  {
    id: 'res_system_design_primer',
    title: 'The System Design Primer',
    provider: 'Donne Martin',
    url: 'https://github.com/donnemartin/system-design-primer',
    type: 'free_book',
    duration: '100 hours',
    skills: ['System Design', 'Scalability', 'Databases', 'Architecture', 'Caching'],
    domains: ['backend', 'fullstack', 'devops'],
    minTier: 'mid',
    maxTier: 'senior',
    description: 'Learn how to design large-scale systems with this comprehensive open-source guide.',
    isFree: true,
    featured: true
  },
  {
    id: 'res_fastapi_docs',
    title: 'FastAPI Official Documentation',
    provider: 'Tiangolo',
    url: 'https://fastapi.tiangolo.com/',
    type: 'official_docs',
    duration: 'Self-paced',
    skills: ['Python', 'FastAPI', 'REST APIs', 'Backend'],
    domains: ['backend', 'datascience', 'aiml'],
    minTier: 'entry',
    maxTier: 'senior',
    description: 'Highly detailed, interactive documentation for building fast APIs with Python.',
    isFree: true
  },
  {
    id: 'res_kaggle_courses',
    title: 'Kaggle Free Micro-Courses',
    provider: 'Kaggle',
    url: 'https://www.kaggle.com/learn',
    type: 'interactive_guide',
    duration: '50 hours',
    skills: ['Python', 'Pandas', 'Machine Learning', 'Data Visualization', 'SQL'],
    domains: ['datascience', 'aiml'],
    minTier: 'intern',
    maxTier: 'mid',
    description: 'Short, practical data science courses covering everything from Python basics to Deep Learning.',
    isFree: true,
    featured: true
  },
  {
    id: 'res_yt_karpathy_neural_nets',
    title: 'Neural Networks: Zero to Hero',
    provider: 'Andrej Karpathy',
    url: 'https://www.youtube.com/playlist?list=PLAqhIrjkxbuWI23v9cThsA9GvCAUhRvKZ',
    type: 'youtube_playlist',
    duration: '20 hours',
    skills: ['Deep Learning', 'PyTorch', 'Neural Networks', 'AI', 'Machine Learning'],
    domains: ['aiml', 'datascience'],
    minTier: 'junior',
    maxTier: 'senior',
    description: 'A deep dive YouTube playlist into building neural networks from scratch by a leading AI researcher.',
    isFree: true,
    featured: true
  },
  {
    id: 'res_kube_docs',
    title: 'Kubernetes Official Tutorials',
    provider: 'CNCF',
    url: 'https://kubernetes.io/docs/tutorials/',
    type: 'official_docs',
    duration: '40 hours',
    skills: ['Kubernetes', 'Orchestration', 'DevOps', 'Containers'],
    domains: ['devops', 'backend'],
    minTier: 'mid',
    maxTier: 'senior',
    description: 'Interactive tutorials for deploying and managing applications on Kubernetes.',
    isFree: true
  },
  {
    id: 'res_aws_skillbuilder',
    title: 'AWS Skill Builder (Free Tier)',
    provider: 'Amazon Web Services',
    url: 'https://skillbuilder.aws/',
    type: 'interactive_guide',
    duration: '100 hours',
    skills: ['AWS', 'Cloud Computing', 'Architecture', 'DevOps'],
    domains: ['devops', 'backend', 'fullstack', 'datascience', 'aiml'],
    minTier: 'entry',
    maxTier: 'senior',
    description: 'Official free digital training from AWS covering foundational cloud concepts to advanced architectures.',
    isFree: true
  },
  {
    id: 'res_owasp_top_10',
    title: 'OWASP Top 10',
    provider: 'OWASP Foundation',
    url: 'https://owasp.org/www-project-top-ten/',
    type: 'official_docs',
    duration: '10 hours',
    skills: ['Security', 'Web Security', 'Vulnerabilities', 'Risk Assessment'],
    domains: ['cybersecurity', 'fullstack', 'backend', 'devops'],
    minTier: 'entry',
    maxTier: 'senior',
    description: 'The standard awareness document for developers and web application security.',
    isFree: true,
    featured: true
  },
  {
    id: 'res_portswigger_academy',
    title: 'Web Security Academy',
    provider: 'PortSwigger',
    url: 'https://portswigger.net/web-security',
    type: 'interactive_guide',
    duration: '150 hours',
    skills: ['Cybersecurity', 'Penetration Testing', 'Web Security', 'Burp Suite'],
    domains: ['cybersecurity'],
    minTier: 'junior',
    maxTier: 'senior',
    description: 'Free, interactive web security training from the creators of Burp Suite.',
    isFree: true,
    featured: true
  },
  {
    id: 'res_you_dont_know_js',
    title: 'You Don\'t Know JS Yet',
    provider: 'Kyle Simpson',
    url: 'https://github.com/getify/You-Dont-Know-JS',
    type: 'free_book',
    duration: '40 hours',
    skills: ['JavaScript', 'Advanced Syntax', 'Closures', 'Async Programming'],
    domains: ['frontend', 'fullstack'],
    minTier: 'junior',
    maxTier: 'senior',
    description: 'A popular open-source book series diving deep into the core mechanisms of JavaScript.',
    isFree: true
  }
];
